// Learn more about DAX queries at https://aka.ms/dax-queries

// Here is a sample DAX query from your model, click 'Run'
// Try other DAX queries by right clicking a table, column, or measure in the data pane and choosing one from 'Quick queries'
DEFINE
	MEASURE 'Measure Table'[Ranking] = 
		RANKX(ALL('fact_stock_price'), [Total Volume]) 
EVALUATE
SELECTCOLUMNS('dim_calendar', "Date", 'dim_calendar'[Date], "Symbol", 'dim_stocks'[symbol], "Rank", [Ranking])  